### ISSUE TITLE
Multiple requests on a single Session with different client certs behave incorrectly

### ISSUE THREAD

**Issue by alex** [requests/requests#2863]
Consider the following code:

``` py
import requests

s = requests.session()
s.get("https://host", cert="path/to/cert1.pem")
s.get("https://host", cert="path/to/cert2.pem")
```

`requests` will silently reuse the same connection for both connections, which is incorrect.

**Comment by Lukasa** [comment]
Yeah, this is not good. We have a similar problem if a user switches the 'verify' flag as well, so we need to fix that.

**Comment by Lukasa** [comment]
So, @shazow, I think really we need to adjust the connection pooling logic in urllib3 a bit. Keying connections off the URL isn't really enough: for HTTPS connections we need to key them off the various connection state parameters as well (cert_reqs, ca_certs, ca_cert_dir, client cert parameters). That's pretty gross because it's a major API change.

Thoughts?

**Comment by shazow** [comment]
Hm I think we had this discussion before somewhere and the conclusion is that we need to avoid exposing per-request cert configs?

**Comment by shazow** [comment]
Maybe we need to make the PoolManager keying more configurable in general, though?

**Comment by catlee** [comment]
I think I'm hitting the same problem where I want to change the auth between requests, but it looks like the first set of credentials gets used for all requests.

**Comment by Lukasa** [comment]
Yup, this is a known issue. It's on my list to fix, but don't expect the fix to be soon. =)

**Comment by catlee** [comment]
is there a workaround?

**Comment by Lukasa** [comment]
The best workaround at this time is to avoid using a Session or, if you are using one of the non-connection-pooling features of the Session, to run a TransportAdapter that never pools connections.

**Comment by catlee** [comment]
I'm using the Session to track cookies. I'll look into alternate
TransportAdapters, thanks.

**Comment by catlee** [comment]
Would it be possible to add this limitation to the docs? I lost several
hours of work debugging this today.

**Comment by Lukasa** [comment]
We could do, but I think it'd be better long-term if we made a move to fix it instead.

**Comment by Lukasa** [comment]
@catlee My gift to you is the first part of the work required for this: shazow/urllib3#751.

**Comment by Lukasa** [comment]
I'm working on this now as part of #2863.

**Comment by jeremycline** [comment]
Hi all. I would be very excited if this particular issue got resolved and would be more than willing to contribute my time to make that happen. I've spent a bit of time poking around in both urllib3 and requests, but I'm still pretty new to both libraries.

Is the plan to get https://github.com/shazow/urllib3/pull/751 into a satisfactory state and then refactor the `requests.adapters.HTTPAdapter` to use the new API? It seems like the urllib3 pull request is stalled because of design uncertainty, so I'm not sure there's a lot I can do there (especially since I don't really know what I'm doing yet). Is there anything else I can do to help?

**Comment by Lukasa** [comment]
Yeah, essentially that's the plan. Last I checked, I think @shazow and I were unclear on exactly the direction that change should take.

**Comment by zestyping** [comment]
I just ran into this and struggled at some length.  Here's a quick doc change to prevent others from suffering the same fate: https://github.com/kennethreitz/requests/pull/3200

**Comment by sigmavirus24** [comment]
This should be fixed by #3109. Once that's done, we can close this out.

**Comment by alex** [comment]
Should this be closed now?

**Comment by nateprewitt** [comment]
Yep, it looks like Jeremy's kw work solved this. Thanks for pinging @alex!
