### ISSUE TITLE
Concerns about 3.0.0 Plans (cryptography)

### ISSUE THREAD

**Issue by kennethreitz** [requests/requests#4109]
As @Lukasa and I discussed at PyCon, `twisted[tls]`, as it stands, would be a dependency of Requests for version 3.0.0. 

I have major concerns for this, as I struggled a lot to get `crypography` to install properly on Linux this weekend. 

We need to ensure that if we plan to to do this, before we put all the work in, that zero installation issues will be had by any of our users. 

One of the reasons we are popular and well-loved is the fact that we have no installation pains, compared to some other libraries. I think we may need to contribute to `cryptography` (potentially by just making suggestions, or otherwise) in order for this to be a tenable plan for us.

-----------------

Correct me, of course, if I'm unfounded in any of my concern @Lukasa. 

Any thoughts?

**Comment by alex** [comment]
So, the biggest thing we're planning to improve this is that we're looking into shipping Linux wheels. /cc @reaperhulk

The major blocker for doing that is making pyOpenSSL able to find certificates (not relevant for requests, because `certifi`, but still needed for other consumers). Once that happens we can ship wheels which will help anywhere that can use `manylinux1` wheels.

We already have wheels on macOS and Windows, so both of those should be good.

**Comment by kennethreitz** [comment]
fantastic news!

**Comment by Lukasa** [comment]
So, yes: in the current climate `twisted[tls]` would be mandatory. That may not remain true: there are some rumblings in python-dev about the possibility of backporting the `SSLObject` class from the standard library to 2.7: if that happened, Twisted could be updated to provide TLS using the standard library instead of or as well as with PyOpenSSL, which would resolve our concerns.

Longer term, we'd like to use platform-native TLS implementations where possible, which requires a bunch of other code.

As a general note, I don't think we're likely to be able to do anything that @alex and @reaperhulk can't. They've been worrying about this problem a lot more than we have.

**Comment by reaperhulk** [comment]
As @alex said we're planning on shipping a `manylinux1` wheel soon-ish. This will make it an easy install under these conditions:

* A sufficiently new `pip` (8.1+)
* The linux distribution is manylinux1 compatible (excludes Alpine linux and any other distribution using musl libc)

So it's a big improvement but there will still be users not covered.

And just for fun, here's the statistics on pip major version for the last month out of PyPI:
![image](https://cloud.githubusercontent.com/assets/161495/26584611/0634c676-450f-11e7-948e-d3f3c614aaa6.png)

**Comment by alex** [comment]
PEP for the `ssl` module backport: https://github.com/python/peps/blob/master/pep-0546.txt

**Comment by kennethreitz** [comment]
Concerns resolved :)
