### ISSUE TITLE
How to respond to Form Submit click?

### ISSUE THREAD

**Issue by scheung38** [requests/requests#4170]
How to respond to Form on HTML click and requests.post triggered as a response? Most examples showing it 

    r = requests.post(...)

but how to bind this to respond to Button on Form in HTML clicked?

     <form method="post" class="navbar-form navbar-right" action="/shorten_url">
          <div class="form-group">
            <input type="text" id="url" name="url" class="form-control input-lg chat-input" placeholder="URL" />
                   <button type="submit" class="btn btn-lg btn-info">Submit</button>
           </div>
      </form>

**Comment by nateprewitt** [comment]
Hey @scheung38, thanks for taking the time to submit this question. As a future reference, we usually prefer to have these kinds of questions posted on https://stackoverflow.com rather than the issue tracker for the project.

Could you briefly clarify what you're looking to do here. Are you trying to submit the form to the server, or trigger another request after the form has been submitted?

If it's the former, you can find the "action" a submit button triggers by looking at the form `action` attribute. In this case it is calling the relative URL path `/shorten_url`. While these are often URL triggers, you may occasionally find calls to javascript functions which Requests does not support.

In this specific example, you'll want to provide a POST request to the full URL (e.g. `http://yourdomain.com/shorten_url`) with a body containing `url=http://theurltoshorten.com`.

```python
r = requests.post('http://yourdomain.com/shorten_url', data={'url': 'http://theurltoshorten.com'})
```

I'm going to close this out for now, but let us know if this isn't what you were asking.
