### ISSUE TITLE
Feature request: timeout on full request completion

### ISSUE THREAD

**Issue by dgillis** [requests/requests#4201]
A simple way to place a timeout on the entire request duration would be very useful. I see this was discussed previously but workarounds involved using additional libraries, signals, etc.

Can this not be fixed by simply modifying `Response.iter_content()` and checking the time after each chunk is read, raising an exception after some "complete_timeout" is surpassed?

I've used a function like  this to do something similar by hijacking the `stream` parameter but it would be nice if this could be built right into `Session` and/or `Response`.

```python
from time import time
import requests

class CompleteTimeout(requests.exceptions.Timeout):
    pass

def request_with_complete_timeout(method, url, complete_timeout, **kwargs):
    """
    Call requests.request() but raise an Exception if the total time exceeds
    complete_timeout seconds.
    """
    kwargs['timeout'] = complete_timeout
    kwargs['stream'] = True
    timeout_time = time() + complete_timeout
    response = requests.request(method, url, **kwargs)
    content_barr = bytearray()
    for chnk in response.iter_content():
        if time() > timeout_time:
            raise CompleteTimeout(
                "Request exceeded complete timeout of {} seconds: {}"
                .format(complete_timeout, url))
        content_barr.extend(chnk)
    response._content = bytes(content_barr)
    return response
```

**Comment by Lukasa** [comment]
> Can this not be fixed by simply modifying Response.iter_content() and checking the time after each chunk is read, raising an exception after some "complete_timeout" is surpassed?

Not really. This won't prevent `iter_content` potentially blocking well past any such timeout, because the socket reads may take a very long time, as may the buffering until the `iter_content` read size. This also ignores all problems with such a timeout while reading the response. 

Ultimately this is a problem of library structure: the way we use the underlying libraries makes expressing his semantic very difficult. We acknowledge it's a problem and hope to remove httplib in order to take steps towards fixing it. However, until that time we're stuck with the semantic we have now.

**Comment by dgillis** [comment]
Thank you. I figured it would have been already added if it were as simple as what I had suggested.
