### ISSUE TITLE
If there is a value in the body, setting the content-length in the header does not transfer it.

### ISSUE THREAD

**Issue by kssim** [requests/requests#4253]
If there is a value in the body, setting the content-length in the header does not transfer it.
I wonder if you are willing to give me the option to ignore the body value and pass in the value set by content-length
If you are thinking about providing options, I am willing to send a pull-request

## Expected Result
I set the header to a content-length of 100, and the size of the body is 10.
I expected the content-length to be 100, but actually it was 10.

## Actual Result
Looking at the code, there was logic to update the content-length by calculating the value of the body if it had a value for the body.
(requests/models.py - line 515, in prepare_content_legnth method)

## Reproduction Steps
This happens when you set the content-length and enter a different size than the value set in the body.

## System Information
It is not system dependent.

**Comment by nateprewitt** [comment]
Hey @kssim, you should be able to accomplish what you're looking for by creating a PreparedRequest and then modifying the value of the header before sending.

You really shouldn't be sending incorrect content lengths though as this can cause issues for some servers and will often leave sockets hanging open waiting for more data.

Let us know if you're still experiencing issues with the above approach.

**Comment by kssim** [comment]
I know that sending invalid values can affect the server.
I'm trying to validate my server using requests, but I need to intentionally send the wrong value.

So, I asked if you could provide that functionality as a send option, not a formal function.
For example, through a boolean value like allow_redirects

**Comment by nateprewitt** [comment]
Sorry if I didn't provide enough information in the last response. Requests is fully capable of handling your use case, you'll just need to use what we call the "PreparedRequest workflow".

The Content-Length calculation should only be performed when prepare() is called. This will produce a PreparedRequest object which will have the newly computed Content-Length based on the body size. You can override the Content-Length header on the PreparedRequest object and then send it using the send method on a Session.

As for a specific option, the Requests API is fairly frozen at this point. I think it's unlikely we'd provide an option or any further modifications to address this since it's already achievable though other means.

**Comment by kssim** [comment]
Thanks for the kind answer.
I think it's better to override and use it as needed.
Thank you :)
