### ISSUE TITLE
FR: Allow SSL verification to be disabled with an env var

### ISSUE THREAD

**Issue by boosh** [requests/requests#4279]
Summary.

Lots of libraries use `requests`. If there's an error verifying SSL in a third-party library it'd be useful to be able to just set an env var to disable SSL verification while the issue is fixed in the failing library. 

This issue is currently affecting me and [others](https://github.com/GoogleCloudPlatform/google-auth-library-python/issues/192) after upgrading `google-cloud`. Even modifying that library to pass `verify=False` would be no mean feat.

**Comment by boosh** [comment]
I guess it'd make sense if it used the `PYTHONHTTPSVERIFY` env var that [urllib](https://www.python.org/dev/peps/pep-0493/) uses.

**Comment by sigmavirus24** [comment]
@boosh, I believe this has been discussed and soundly rejected before. Please search open **and** closed issues prior to opening new ones. 

Further, the PEP you're referencing is not intended to be used like this. For one thing, it was added because the standard library was *insecure by default* and the transition to making it secure by default was deemed problematic by some. This was an escape hatch to avoid having to update a formerly insecure block of code to properly handle being secure. I don't fully understand what is happening with `google-cloud` but I suspect that the solution to their problem doesn't actually belong here.

**Comment by Lukasa** [comment]
This has been requested before and I think our position is the same: global switches to disable certificate validation are an attractive nuisance that tend to be used to mask actual problems. 

I don't think the brokenness of other libraries requires us to provide this functionality.
