### ISSUE TITLE
redirect(301) always need to wait for 120 seconds

### ISSUE THREAD

**Issue by etiaxie** [requests/requests#4288]
code like this:
import requests
requests.request('get', 'http://10.192.74.230:6201/en?CSnaL/uZkQC9SLVbaMoQDA8Ph9/+Q7+stJc7S1qGSuvEss6zmYfB7SvYE4vAOWgfUrJuxOBk7giWoAKARD9o7oaZlmg84SgIEIvBgnqr3Jj9OH9RPt4MEbQmHmhsDfBfMzY2OA==')

expect return a response with status_code=301 and then will auto send to the new url in "Location" of 301 response.
actually requests.request() will not get a return value until after 120 seconds.and in wireshark log i can see the 301 response received immediatly.

**Comment by etiaxie** [comment]
the received 301 message:
HTTP/1.1 301 Moved Permanently
Location: http://10.192.74.193:6801/en?OquUyLHZ2FyZUDNp2IFFPnft8SvIpFbincdfI+28KZTEss6zmYfB7SvYE4vAOWgfUrJuxOBk7giWoAKARD9o7pP2snF7YaLGUe2u5T4m2HKqrfp1J6hXLT424Rl2iJWSNjkwMA==&&act=get&ztype=0&zvalue=100
Connection: close
Date: Tue, 12 Sep 2017 09:15:20 GMT

**Comment by Lukasa** [comment]
The 301 is setting `Connection: close`, so we're waiting for it to be closed before we continue. This is because 301s may have bodies, and we need to handle that possibility. There's not much we can do about this: the server should either remove `Connection: close` (because it doesn't seem to need it), or it should close the connection immediately.
