### ISSUE TITLE
headers should be a dictionary, it should be a list

### ISSUE THREAD

**Issue by paul-hammant** [requests/requests#4344]
## Summary.

Requests lib has implemented headers as a dictionary, yet the web supports a repeating header with the same key.  Subversion via WebDAV is tech that uses that.  For example, "svn log" sends up:

```
DAV: http://subversion.tigris.org/xmlns/dav/svn/depth
DAV: http://subversion.tigris.org/xmlns/dav/svn/mergeinfo
DAV: http://subversion.tigris.org/xmlns/dav/svn/log-revprops
```

## Expected Result

All three 'A' headers got sent to the server

## Actual Result

Only one did

## Reproduction Steps

```python
foo = requests.request(verb, url, headers={"A": "one", "A": "two", "A": "three"})
```

## System Information

All versions of requests

**Comment by paul-hammant** [comment]
Ha!  You can fool it with trailing spaces on the key:

```
 headers={
     "DAV" : "http://subversion.tigris.org/xmlns/dav/svn/depth",
     "DAV " : "http://subversion.tigris.org/xmlns/dav/svn/mergeinfo",
     "DAV  " : "http://subversion.tigris.org/xmlns/dav/svn/log-revprops"
 }
```

**Comment by sigmavirus24** [comment]
Did you try doing `headers=[('A', 'one'), ('A', 'two'), ('A', 'three')]`? I believe we support this use case when sent that way.

**Comment by ghost** [comment]
`headers` must be a `dict`which is verified here:

https://github.com/requests/requests/blob/54ad3d6dcc173576d3f9784985e88d31a4997677/requests/utils.py#L858-L861

A `list` is not supported.

@paul-hammant What API would you propose to verify multiple-value headers? `headers={"A": "one", "A": "two", "A": "three"}` makes no sense because this is `{'A': 'three'}`. What about a list:

````python
headers = {
    "A": ["1st value of multi-value header", "2nd value of multi-value header],
    "B": "single value header"
}

**Comment by nateprewitt** [comment]
@lutzhorn, I don't believe we'll allow the user to pass a list since it would go against our stance of not guessing on what the user wants in their header.

While we don't currently support a list of tuples, we use that in other places such as the `data` param and it seems like a possible option.

I'm not convinced we need to make a change here though. RFC 7230 states pretty clearly that:
```
3.2.2.  Field Order
   [...]
   A sender MUST NOT generate multiple header fields with the same field
   name in a message unless either the entire field value for that
   header field is defined as a comma-separated list [i.e., #(values)]
   or the header field is a well-known exception (as noted below).
```

So @paul-hammant you should be able to accomplish what you're looking for with something like:

```python
dav_vals = ["one", "two", "three"]
headers = { 'DAV': ','.join(dav_vals)}
foo = requests.request(verb, url, headers=headers)
```

I'm proposing we close this, because this is solvable with one line and probably doesn't warrant the weight of adding tuple support.

**Comment by ghost** [comment]
Yes, the RFC is strict on that. Using `join` is a good idea for how to follow the RFC and accomplish what @paul-hammant  has in mind.

**Comment by ar4s** [comment]
@paul-hammant I think is related to #4290

**Comment by paul-hammant** [comment]
Apache2/Subversion are not as strict as the RFC. No matter - there are multiple ways through this. Thanks for not insta-closing :)
