### ISSUE TITLE
Use another SSL engine than OpenSSL

### ISSUE THREAD

**Issue by hydrargyrum** [requests/requests#4355]
Requests should let the ability to use other SSL backends than OpenSSL (which has numerous problems), for example NSS.

**Comment by Lukasa** [comment]
This is an enormously difficult request to achieve. Python is extremely tightly tied to OpenSSL, and so therefore Requests is too (because it ultimately uses httplib). Changing this would require a very substantial patch, and take an enormous amount of developer time. This is sadly just not a priority for the development team. While we'd welcome a patch to do this, it will need to be organised separately from this project.
