### ISSUE TITLE
pip install : Unable to determine SOCKS version

### ISSUE THREAD

**Issue by torfhub** [requests/requests#4386]
i have try all the method, it just not work !

**Comment by HelioGuilherme66** [comment]
@torfhub If you really have found a problem and expect to have it fixed, what you wrote is not enough.

Start by reading [CONTRIBUTING.md](https://github.com/requests/requests/blob/master/CONTRIBUTING.md)
--
At least post here the command and the output.

**Comment by sigmavirus24** [comment]
Hi @torfhub,

We will need a lot more information in order to help you. Without that information, I'm going to close this, for now. If you leave a comment with information, I'll be happy to reopen this and help you investigate.

---

@HelioGuilherme66 we appreciate your attempt to help gather some basic information with @torfhub. Please, in the future, try to phrase your comments a bit more gently. @torfhub seems rather new to open source software and gruff and unwelcoming responses are not typically helpful for either them or the maintainers.
