### ISSUE TITLE
requests Read timed out when handle two same header in http response

### ISSUE THREAD

**Issue by beruhan** [requests/requests#4438]
I use requests's get method to request a url,I found It always timeout,I use wireshark capture the response, the server has response the data,but why requests's get method timeout?,the response as flows
```
GET /onvif/device_service HTTP/1.1
Host: 50.250.78.211
Connection: keep-alive
Accept-Encoding: gzip, deflate
Accept: */*
User-Agent: python-requests/2.18.4

HTTP/1.1 401 Unauthorized
Date: Tue, 26 Dec 2017 03:24:12 GMT
Server: DNVRS-Webs
Cache-Control: no-cache
Content-Type: text/html
Connection: keep-alive
Keep-Alive: timeout=60, max=99
WWW-Authenticate: Digest realm="DVRNVRDVS", domain="::", qop="auth", nonce="6f43ba833ff06ae8b7b36bd2dfb9704c:1514258652870", opaque="", algorithm="MD5", stale="FALSE"
WWW-Authenticate: Basic realm="DVRNVRDVS"

```
test urls:http://50.250.78.211/onvif/device_service

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

---

I would point out that my browser and cURL both exhibit the same behaviour as requests. The reason is that the server doesn't provide a `Content-Length` header to indicate there is no actual body. As a result, all 3 user agents expect a body that is sent as a chunked response (i.e., as if the server had sent `Transfer-Encoding: chunked` as a header). As a result, Requests waits for any data to come and we eventually timeout.
