### ISSUE TITLE
README does not render properly on PyPI

### ISSUE THREAD

**Issue by johnthagen** [requests/requests#4441]
# Summary

Requests PyPI page does not render, making it much less useful.

## Expected Result

Rendered RST to be shown on https://pypi.python.org/pypi/requests

## Actual Result

Raw unrendered RST:

```
Requests: HTTP for Humans
=========================

.. image:: https://img.shields.io/pypi/v/requests.svg
:target: https://pypi.python.org/pypi/requests

.. image:: https://img.shields.io/pypi/l/requests.svg
:target: https://pypi.python.org/pypi/requests
```

**Comment by alexdarling** [comment]
Could this be due to some invalid RST associated with line 110 of README.rst? I think it needs back-quotes, e.g.

``.. _`Contributor Friendly`: https://github.com/requests/requests/issues?direction=desc&labels=Contributor+Friendly&page=1&sort=updated&state=open``

instead of the current:

``.. _Contributor Friendly: https://github.com/requests/requests/issues?direction=desc&labels=Contributor+Friendly&page=1&sort=updated&state=open``

**Comment by sigmavirus24** [comment]
@alexdarling that shouldn't be the problem. In fact our readme check is passing on CI. I suspect whatever the issue *was* is now fixed.

**Comment by kennethreitz** [comment]
will be fixed in the next release — pypi doesn't allow you to update existing releases any longer!
