### ISSUE TITLE
Max retries exceeded with url

### ISSUE THREAD

**Issue by phanindravarma38** [requests/requests#4453]
Summary.
I am trying to hit a third party API, such as api.ipify.org, which gives IP addresses and read the results. 
## Expected Result
JSON Response From URL i.e. ip address. 
What you expected.

## Actual Result
requests.exceptions.ConnectionError: HTTPSConnectionPool(host=hostname, port=443): Max retries exceeded with url: /myurl (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10a857610>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

What happened instead.

## Reproduction Steps

```python
import time

page = ''
while page == '':
    try:
        page = requests.get("https://api.ipify.org/")
    except:
        print("Connection refused by the server..")
        print("Let me sleep for 5 seconds")
        print("ZZzzzz...")
        time.sleep(100)
        print("Was a nice sleep, now let me continue...")
        continue

```

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

As an aside `nodename nor servname provided, or not known` typically indicates an issue with DNS. It sounds like you're requesting several different URLs that are for several different domains. You should ensure all have domain names and that those domains all work.

**Comment by sigmavirus24** [comment]
Also, entertainingly, your reproduction steps (reproduced below) will always fail because of two problems:

1. You never import `requests` so you get a `NameError`
2. You use `try/except` without catching a specific exception so it will catch the `NameError` and then make you think you've encountered an exception from requests.

```py
import time

page = ''
while page == '':
    try:
        page = requests.get("https://api.ipify.org/")
    except:
        print("Connection refused by the server..")
        print("Let me sleep for 5 seconds")
        print("ZZzzzz...")
        time.sleep(100)
        print("Was a nice sleep, now let me continue...")
        continue
```

**Comment by phanindravarma38** [comment]
Yes, I have imported the requests but in another code block where I have encountered the original problem. 
Just to be clear. I am using IPython notebook. So, If I import in one block it will be imported everywhere i.e. in all the other code blocks.

**Comment by sigmavirus24** [comment]
Regardless, this isn’t the appropriate place for your question. Please post it on StackOverflow
