### ISSUE TITLE
Consider allowing iter_lines to keep end of lines intact

### ISSUE THREAD

**Issue by c4milo** [requests/requests#4466]
I'm using `iter_lines` to read CSV files and it has been working great. However, in one particular case, I had to take the iterable response back to a file-like object and it was not possible because `readlines()` is being called without `keepends=True`. Will it possible to expose this parameter in `iter_lines` or should I write my own line iterator?

**Comment by sigmavirus24** [comment]
Requests is presently under a feature freeze. That means the API is only extended in certain conditions. I'm not sure we'd extend it for this case. Over the years this is the first request we've had for this feature. You're definitely (at the present time) better off writing your own. We can also toss this in the [toolbelt](/requests/toolbelt) and determine how popular it is. If it turns out to be massively popular we can move it into Requests proper.

**Comment by nateprewitt** [comment]
Hi @c4milo, I agree with @sigmavirus24 that this is probably something best suited for the toolbelt. If we get it implemented over there and find there is significant demand, we can revisit. Until then, I don't think we'll plan on making this change. Thanks for taking the time to make sure we were aware of the issue.
