### ISSUE TITLE
Unauthenticated requests turns into authenticated one somewhere

### ISSUE THREAD

**Issue by mittagessen** [requests/requests#4488]
My program uses the github API to query repository data and requests works perfectly for that. I've got a bug report from a user that they get a 401 back when trying to run it, which shouldn't happen as no authentication is involved anywhere. Unfortunately, I can't reproduce the bug myself but lo and behold with sufficient logging verbosity I see on the reporters machine my simple ``requests.get(url)`` request somehow gets Basic Authentication data attached to it.

From a cursory look over the source code I couldn't find any external source of authentication data but I only looked for obvious stuff like environment variables.

## Expected Result

When executing ``requests.get('https://api.github.com/repos/mittagessen/kraken-models/git/refs/headers/master')`` I expect this (urllib3 debug loggin):

```
send: 'GET /repos/mittagessen/kraken-models/git/refs/heads/master HTTP/1.1\r\nHost: api.github.com\r\nConnection: keep-alive\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nUser-Agent: python-requests/2.18.4\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
```

HTTP request to go over the wire.

## Actual Result

Instead I get this:

```
send: b'GET /repos/mittagessen/kraken-models/git/refs/heads/master HTTP/1.1\r\nHost: api.github.com\r\nUser-Agent: python-requests/2.18.4\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nAuthorization: Basic bG9yYW5nZXI6MmEzYWM3MjFmZWI0NjlmYjg0YTQ2NzFmNGI1ZjU3MGIyMGRjZTdjNw==\r\n\r\n'
reply: 'HTTP/1.1 401 Unauthorized\r\n'
```

## Reproduction Steps

Unfortunately, I can't reproduce it on any of my machines.

## System Information

Sorry, I don't have the help output but the reporter's machine run macOS 10.12.6 and the error occurs with both python 2.7 and 3.6. requests version is 2.18.4 as can be seen from the logging.

**Comment by nateprewitt** [comment]
Hey @mittagessen, my guess is the person using your tool has a `.netrc` file setup. This can be configured to work with Github credentials which they've likely done. You can see that this information will be used when determining auth choices [here](https://github.com/requests/requests/blob/512066488e039e048ff255d8322fbb53642166bd/requests/sessions.py#L429).

I'm going to close this out for now since this doesn't appear to be a defect in Requests. If you have further questions, please open a question on [StackOverflow](https://stackoverflow.com) with the `python-requests` tag and we'll be happy to continue the conversation there. Thanks!

**Comment by mittagessen** [comment]
Sorry, I must have missed that part. It is even documented and I feel stupid now.
