### ISSUE TITLE
Trying to install requests

### ISSUE THREAD

**Issue by LucienRapilly** [requests/requests#4530]
I tried to install requests with

cd /tmp && curl -OL https://github.com/kennethreitz/requests/zipball/master && unzip master && cd requests* && sudo python setup.py install

and i got this :

curl: (35) error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

I also tried :

curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
sudo python get-pip.py #install pip packet manager for python
sudo pip install request

and I got :

python: can't open file 'get-pip.py': [Errno 2] No such file or directory

Thanks for your help !

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

To note, all of the errors you're getting are completely unrelated to Requests.

> curl: (35) error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

Is specifically from `curl`. It seems that `curl` isn't downloading the pip bootstrap either. Your system is the source of all your problems here.
