### ISSUE TITLE
ChunkedEncodingError: Connection broken: error 54 ECONNREST

### ISSUE THREAD

**Issue by yzlasu** [requests/requests#4532]
Summary.
When using requests.request('Get', 'https://hazards.fema.gov/gis/nfhl/services/public/NFHLWMS/MapServer/WMSServer?REQUEST=GetCapabilities&service=WMS&version=1.1.0'), the described error was thrown out.

## Expected Result
The true value should be a XML document, which could be preview using the Chrome browser to open the link in the request.

## Actual Result

What happened instead. The described error was thrown.

## Reproduction Steps

```python
import requests
requests.request('Get', 'https://hazards.fema.gov/gis/nfhl/services/public/NFHLWMS/MapServer/WMSServer?REQUEST=GetCapabilities&service=WMS&version=1.1.0')
```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  }, 
  "cryptography": {
    "version": "2.1.3"
  }, 
  "idna": {
    "version": "2.6"
  }, 
  "implementation": {
    "name": "CPython", 
    "version": "2.7.14"
  }, 
  "platform": {
    "release": "15.6.0", 
    "system": "Darwin"
  }, 
  "pyOpenSSL": {
    "openssl_version": "1010007f", 
    "version": "17.3.0"
  }, 
  "requests": {
    "version": "2.18.4"
  }, 
  "system_ssl": {
    "version": "100020ef"
  }, 
  "urllib3": {
    "version": "1.22"
  }, 
  "using_pyopenssl": true
}
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

Further, `ECONNRESET` means that the server is resetting the connection. The fact that it's a chunked encoding error means that the server is resetting your connection while giving you chunked data. It seems this is a problem with the server

**Comment by sigmavirus24** [comment]
Also, using the exact code you gave me, I do not get an exception but instead a 200 response.
