### ISSUE TITLE
PEM lib SSL error

### ISSUE THREAD

**Issue by kevr** [requests/requests#4587]
Summary.

See https://github.com/requests/requests/issues/3702

What you expected.

A correct connection or failure to verify ssl error

What happened instead.

SSL library traceback

```
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
SSLError: [X509] PEM lib (_ssl.c:2831)
```

Reopening this previously closed issue.

**Comment by nateprewitt** [comment]
Hi @kevr, thanks for taking the time to open this. So this error is a cert problem, as stated in the other ticket. We'd need the exact version of Python 2.7 you're using but it's likely coming out of [this function](https://github.com/python/cpython/blob/a61f5da54772b0ea6a7eccf21df08e61585ef712/Modules/_ssl.c#L2828-L2884). While the problem is pretty easy to find with a google search, I agree that the error message leaves something to be desired.

Since this exception is being raised from the standard library, the only fix is likely wrapping it and rethrowing a clearer message. If that work was done, it would be handled at a layer lower than Requests though. Either in [urllib3](https://github.com/urllib3/urllib3) or more likely in pyopenssl/cryptography. I'd suggest raising an issue there. Thanks!

**Comment by kevr** [comment]
Thanks for the quick response @nateprewitt -- I understand this is a certificate issue, however, I don't see a specific error message as to why; I guess the code basically says that what's being loaded is not in ASN1 or PEM format. Alright, thank you a lot.
