### ISSUE TITLE
OSError / Image.open(BytesIO(r.content))

### ISSUE THREAD

**Issue by Liuzhj** [requests/requests#4595]
Summary.

## Expected Result

http://docs.python-requests.org/en/latest/user/quickstart/?highlight=binary#binary-response-content

```py
from PIL import Image
from io import BytesIO
i = Image.open(BytesIO(r.content))
```

```
Traceback (most recent call last):
  File "X:/study/test.py", line 7, in <module>
    i = Image.open(BytesIO(r.content))
  File "C:\Program Files\Python35\lib\site-packages\PIL\Image.py", line 2590, in open
    % (filename if filename else fp))
OSError: cannot identify image file <_io.BytesIO object at 0x0000000003471AF0>
```

python : 3.5.1
OS: Windows 7

**Comment by Liuzhj** [comment]
I don't know how to solve it , give me a hand ,Thanks .

**Comment by nateprewitt** [comment]
Hi @Liuzhj, this appears to be a request for help rather than a defect report for Requests. We recommend directing usage questions to [StackOverflow](https://stackoverflow.com) for assistance.

To help direct your question, it looks like you’re either misusing `image.open` or `r.content` is not an image. Either way the problem seems to lie outside of Requests.

**Comment by Liuzhj** [comment]
hi @nateprewitt 

this [**url**](http://docs.python-requests.org/en/latest/user/quickstart/?highlight=binary#binary-response-content)  is official of Requests。

this code is copy from official documents, but is can't running 

![image](https://user-images.githubusercontent.com/14147011/38914404-cc7bcdc4-4311-11e8-9217-c7f355ecfdd2.png)

**Comment by nateprewitt** [comment]
@Liuzhj as I said the value of `r.content` is not an image `pillow` can parse then. Please direct further questions on usage to StackOverflow, thank you!
