### ISSUE TITLE
requests follow 302 redirection but didn't change the 'Host' header accordingly.

### ISSUE THREAD

**Issue by 1600** [requests/requests#4665]
when using requests with sites that returns a 302 Moved Temporarily, and in the response header there will be a 'Location' header given the target redirect domain.
Now if you also defined the 'Host' header in a headers parameter to be  some fixed domain, the redirect won't be correctly performed.

for example:
## Expected Result
using requests to access https://login.website.com, while customizing headers= {'Host':'login.website.com'}
website returns 302 with 'Location' header > 'https://someothersubdomain.website.com/1.html'
at this moment I expected it redirects correctly to https://someothersubdomain.website.com

## Actual Result
it follows redirect to "https://login.website.com/1.html" rather than the correct someothersubdomain.website.com
inspecting the second http requests automatically sent by 'requests' we can see that the host header is incorrectly persisted to 'login.website.com'

## Reproduction Steps
like I described above.

```python
import requests
url = 'some url that redirect to another subdomain'
headers= {'Host':'login.website.com'}   
res = requests.get(url,headers=headers)
```

## System Information

    $ python -m requests.help

{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "1.8.1"
  },
  "idna": {
    "version": "2.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.6.1"
  },
  "pyOpenSSL": {
    "openssl_version": "100020bf",
    "version": "17.0.0"
  },
  "requests": {
    "version": "2.18.4"
  },
  "system_ssl": {
    "version": "100020bf"
  },
  "urllib3": {
    "version": "1.22"
  },
  "using_pyopenssl": true
}

**Comment by sigmavirus24** [comment]
Hi there @1600 

I went looking in our documentation for where we have this clearly explained and am having trouble finding it right now. The short answer is:

There are headers (`Host`) included that if the user specifies, Requests does not alter. This means if you want the right thing to be done with your request involving the `Host` header, you have to take full control over the redirect process yourself. We will not change that out without your consent.

This is not a bug, as not stepping on users' toes is a intentional design choice.

Cheers,
Ian

**Comment by 1600** [comment]
I think maybe someone wants to be redirected to the same domain, but most of the time they don't.

**Comment by sigmavirus24** [comment]
@1600 not so much a feature as much as "We handle that for you, so when you want to specify it we don't know exactly what you want us to do" because there are a few behaviours people expect. So we make the decision of not forcing one and giving everyone the ability to do a little more work to get exactly what they expect.
