### ISSUE TITLE
Add current request url tip when ConnectionError

### ISSUE THREAD

**Issue by ChandlerBent** [requests/requests#4670]
I got an error about "ConnectionError" when I using thirdparty sdk to request server.
The thirdparty sdk is using requests to request server.
`
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
`

I spent a long time looking for the error.
I print the request url from sdk source code, finally know why I get the error.
The sdk server domain has changed "https", but sdk source code still use "http".
Error message never tell me current url is "http" or "https".

If I can get the request url from error message, I will know how to fix that as soon as.

**Comment by nateprewitt** [comment]
Hi @ChandlerBent, thanks for the suggestion! There are a host of reasons a server might close the connection prematurely, many of which are not specific to the scheme choice. We are raising this exception from an underlying library (urllib3, which raises it from the standard lib) and don't modify its contents in Requests.

My hunch is that you don't have `requests[security]` installed and which is possibly why you're having issues connecting. It's hard to tell without the information requested when opening these issues. I'm not sure that adding the url into the exception message would provide an obvious answer in the common case. Many times people are specifically requesting an https url in this case, rather than receiving a redirect.

Given that there's answers to this readily available in the closed issues section or with a quick google search for the exception message, I'm not sure there's much more to do here in Requests.
