### ISSUE TITLE
TLSV1_ALERT_PROTOCOL_VERSION Error when requesting https sites

### ISSUE THREAD

**Issue by asherbig** [requests/requests#4757]
I get the error "**ssl.SSLError: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:598)**" when attempting to access https sites. This is the specific site I got the error on https://www.apartments.com/westhampton-court-apartment-homes-atlanta-ga/sqpw607/ I've been stuck on this issue for over a day at this point, please help.

## Expected Result
I expect to get the data from the URL, not get an error.

## Actual Result
I get the error specified above.

## Reproduction Steps
Try accessing any https site.
requests.get(url)

## System Information
I am on OSX Yosemite 10.10.5 (14F2511)

**python --version**: Python 3.7.0

**import ssl; pprint(ssl.OPENSSL_VERSION)**: 'OpenSSL 0.9.8zg 14 July 2015' (ran from my script)

**openssl version -a**: 
OpenSSL 1.0.2o  27 Mar 2018
built on: reproducible build, date unspecified
platform: darwin64-x86_64-cc
options:  bn(64,64) rc4(ptr,int) des(idx,cisc,16,int) idea(int) blowfish(idx) 
compiler: clang -I. -I.. -I../include  -fPIC -fno-common -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -arch x86_64 -O3 -DL_ENDIAN -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
OPENSSLDIR: "/usr/local/etc/openssl"

**nano .bash_profile**: 
PATH="/Library/Frameworks/Python.framework/Versions/3.4/bin:${PATH}"
export PATH

export PATH="/opt/local/bin:/opt/local/sbin:$PATH"

export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/opt/openssl/bin:$PATH"
export PATH="/usr/local/opt/python/libexec/bin:$PATH"

**Comment by sigmavirus24** [comment]
Hi there! Thanks for opening this issue. Unfortunately, it seems this is a request for help instead of a report of a defect in the project. Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.

---

As an aside, your python is using openssl 0.9.8 which doesn't support anything over TLS v1.0 if I remember correctly and per [StackOverflow](http://stackoverflow.com/questions/44316292/ddg#44316583) the website wants to use a higher version of TLS which you're openssl does not support. Futhermore, 3.7.0 was supposed to require a more modern version of openssl so how you've compiled your python to use this ancient version is beyond me. Finally, you completely ignored the request for debugging information we have in the template. Further issues opened like this will be closed immediately.
