### ISSUE TITLE
encoding double backslash

### ISSUE THREAD

**Issue by mharol** [requests/requests#4758]
Summary.
Downloading files with \\ in query strings doesn't encode properly

**Comment by nateprewitt** [comment]
@mharol it sounds like you're passing double backslashes as a string to Requests. Python's native strings are going to treat this as an escape character when passing it to urlencode which is why you're seeing the single %5C. You'll need to pass a raw string (`r'\\'`) with the backslashes if you want them to be interpreted literally.
