### ISSUE TITLE
requests.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:645)

### ISSUE THREAD

**Issue by xiantang** [requests/requests#4759]
Please refer to our [Stack Overflow tag](https://stackoverflow.com/questions/tagged/python-requests) for guidance.
when i open 32 threads,requets raise this exception.

**Comment by xiantang** [comment]
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "2.2.2"
  },
  "idna": {
    "version": "2.7"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.5.2"
  },
  "platform": {
    "release": "4.15.0-29-generic",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "1010008f",
    "version": "18.0.0"
  },
  "requests": {
    "version": "2.19.1"
  },
  "system_ssl": {
    "version": "1000207f"
  },
  "urllib3": {
    "version": "1.23"
  },
  "using_pyopenssl": true
}

**Comment by nateprewitt** [comment]
Hi @xiantang, it doesn't look like there is an obvious link to a specific stack overflow question. This issue tracker is specifically for defects in Requests. The error you're providing is related to a remote server closing the connection on us which we can't do anything about. It's likely you may be being forcibly throttled by the server due to the number of threads you're using.

I'm going to close this for now since we don't have anything suggesting a bug in Requests. If you'd like to leave a link to the StackOverflow question, we can look at following up over there. Thanks!
