### ISSUE TITLE
POST, PUT and PATCH on 301 redirect re-POST without body

### ISSUE THREAD

**Issue by skybobbi** [requests/requests#4773]
Summary.

If ``allow_redirects = True`` and if redirect response 301 is returned, then POST, PUT and PATCH requests should save body.
Similar [issue 1084](https://github.com/requests/requests/issues/1084) was satisfied  for 307 responses.
[RFC](http://www.faqs.org/rfcs/rfc2616.html) says the same thing about 307 and 301 responses.

Actual result - body is cleaned on 301 response.

Requests version 
```
requests==2.19.1
```

**Comment by nateprewitt** [comment]
Hi @skybobbi, the RFC linked is quite outdated. I believe you may have meant RFC 7231 section 6.4.2, which discusses changing POST to GET on redirect.

This behavior was implemented in Requests quite a while ago and is intentional. There is potential for malicious redirects to capture the contents of what you’re trying to send to another server. You’ll find this is implemented by every major browser and many http-related tools.

That said, we did revisit this a year or two ago and decided we’d scope the body stripping down to only POST requests per the RFC. This code is merged into the current 3.0 branch but won’t be released in the 2.X series due to it being a breaking change.

**Comment by jokejuke** [comment]
Thanks. 
As I understood, all request types except POST will save body on 301 redirects since 3.* version of requests. Am i right?

**Comment by nateprewitt** [comment]
@skybobbi 3.0 has not been released yet, but yes, that is the functionality that is currently implemented on that branch.

If you need to handle this in the interim, you’ll need to handle the redirecting in your code. I would suggest looking at the SessionRedirectMixin in sessions.py

**Comment by jokejuke** [comment]
Thank you!
