### ISSUE TITLE
Can't set ipv6 proxy

### ISSUE THREAD

**Issue by deounix** [requests/requests#4788]
I'm trying to use ipv6 proxy with requests but I can't

What I'm doing is :

```
import requests

resp = requests.get('https://instagram.com', proxies=dict(http='https://xxxxxx:xxxxxx@[2604:0180:2:99b:fc3d:a70b:a7f2:7a2a]:17684', https='https://xxxxxx:xxxxxx@[2604:0180:2:99b:fc3d:a70b:a7f2:7a2a]:17684'))
```

**Comment by nateprewitt** [comment]
Hi @deounix, we’re going to need more information to look into this.

Please provide answers to the questions originally asked in the issue template, an explanation of what you’re experiencing vs what you’re expecting, and a stack trace if applicable. Thanks!

**Comment by deounix** [comment]
Hi @nateprewitt, There is no issue template just link to stackoverflow site.

I just need to know how can I set ipv6 proxy in requests. so I can do simple HTTP requests.

**Comment by nateprewitt** [comment]
@deounix, the "Request for Help" template is asking for you to pose usage questions on Stackoverflow first, rather than posting them on the issue tracker. We’ll review the template and try to make that clearer.

The other issue template for reporting a bug has a series of questions. Without that information, it’ll be difficult to accurately diagnose why the ipv6 proxy setup may not be working.

Can you please also verify your proxy is working with curl or some other http client?

**Comment by deounix** [comment]
@nateprewitt Thank u I think curl help me to find the problem. Instagram didn't accept the connection but google, fb ... etc accept don't know why but I think this issue located to instagram.
