### ISSUE TITLE
Issue Passing All Tests in Suite

### ISSUE THREAD

**Issue by josephlane** [requests/requests#4803]
Hello,

In my efforts to start contributing to the requests codebase, I've run into an issue with one of the test.

<img width="1306" alt="screen shot 2018-09-22 at 8 59 54 am" src="https://user-images.githubusercontent.com/1155601/45918043-6538a780-be46-11e8-9acf-44a6fc2042a4.png">

This issue seems to relate to https://github.com/requests/requests/issues/3732 in some way but I've had no luck in tracing down the exact culprit.

The two items that stand out to me are:

> pytest-httpbin server hit an exception serving request: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:661)
> attempting to ignore so the rest of the tests can run

and

> Failed: DID NOT RAISE <class 'requests.exceptions.ConnectionError'>

Steps to reproduce against my current configuration:

I'm executing these test by tying in "Pytest" in the requests directory.

Any help will be greatly appreciated.

**Comment by nateprewitt** [comment]
Hi @josephlane, it sounds like you have something on your network that may be intercepting this request and routing it somewhere else. Typically, this won't resolve to a valid IP address since it's not an actual service. Since the request is not over https, we don't have a way to prevent interception from happening. I would verify you don't have some sort of network manager, proxy, or possibly a bad actor intercepting this request.
