### ISSUE TITLE
HTTPConnectionPool(host='207.45.249.157', port=80): Max retries exceeded with url: http://www.google.com/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000234AC984898>: Failed to establish a new connection: [WinError 10060]

### ISSUE THREAD

**Issue by ImARegularUser** [requests/requests#4857]
Hi, I'm working on a python project, I use python3 with anaconda

I'm trying to execute a simple get request with this code:

import requests

proxies = {'http' : 'http://207.45.249.157',
                'https': 'https://207.45.249.157'}

r = requests.get('http://www.google.com/', proxies=proxies)

and I get this error as a result:

ProxyError: HTTPConnectionPool(host='207.45.249.157', port=80): Max retries exceeded with url: http://www.google.com/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000234AC984898>: Failed to establish a new connection: [WinError 10060]')))

I'm quite new to python, especialy to the requests module

Thanks

**Comment by nateprewitt** [comment]
Hi @ImARegularUser, welcome to the world of Python! The issue you’re seeing here is with your proxy rather than Requests. I’d suggest reviewing the [proxy docs](
http://docs.python-requests.org/en/master/user/advanced/#proxies) and debugging from there. For future reference, we prefer usage questions to be directed towards StackOverflow with the python-requests tag since this issue tracker is reserved for defects in Requests. Thanks!

**Comment by ImARegularUser** [comment]
Alright, Thanks for you reply and sorry for the mistake x)
