### ISSUE TITLE
InvalidURL: URL has an invalid label. 

### ISSUE THREAD

**Issue by PranayWankhede** [requests/requests#4904]
I am getting the following exception for the URL which has underscore in it. After going through https://github.com/requests/requests/issues/3683 I got to know that this issue is only for the request library version >= 2.12. But i encountered similar issue for 2.11.1. Are there any changes to the older versions? Thanks!

**Comment by nateprewitt** [comment]
@PranayWankhede, the issue being discussed in #3683 was resolved in 2.12.2. As stated in that issue, Requests has no intent to support URIs with underscores in hostnames because those are expressly prohibited in the URI RFC.

If you’re still experiencing this issue prior to 2.12, it’s likely another issue because we did not use idna to validate hostnames at that point. We’d need a concrete example to do anymore debugging here. I’m going to close this for now since this seems like a usage inquiry for unsupported behavior. If you have a use case that’s causing this with a URI that conforms to spec, please feel free to reopen. Thanks!
